language: objective-c
osx_image: xcode8.3

env:
  - ACTION=test  PLATFORM=Mac     DESTINATION='platform=OS X'
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 7'
  - ACTION=build PLATFORM=watchOS DESTINATION='platform=watchOS Simulator,name=Apple Watch Series 2 - 42mm'
  - ACTION=test  PLATFORM=tvOS    DESTINATION='platform=tvOS Simulator,name=Apple TV 1080p'
  
before_install:
  - xcrun simctl delete 25EF4763-1942-4A3B-A80F-FC080592B82C

script:
  - set -o pipefail && xcodebuild $ACTION -project ArithmeticDate.xcodeproj -scheme ArithmeticDate -destination "$DESTINATION" | xcpretty -c

before_deploy:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage build --no-skip-current
  - carthage archive ArithmeticDate

deploy:
  provider: releases
  api_key:
    secure: GPIXE4qibKhow2ak4f4YLZAxvqAK4k4Ry3u8Pb12D4o+oHZzlobX0i+xzrgWdKJcDP6AZwafDi8qIgaNyB5ggXMv8lKeVZingAVz9DDUK0/ZPQlovvqWaGsPuEDkzC33kA320xbK7YkEuFaixcoyh3VzxX37fWomOLqHvRsARMNhbnV1yEuZGIXfCH2d09HJlnCinogf6bzZYfIKpxJzGnGO0k97MmMUxxaSqZ24BGh9LeoslzF/xeyochSevdrmJKEZzk4yNJg2RCRAM319EORvVvaAhCNwr1ldeSRWDjdBEJ4d70P8fip5/oTivfQwdO89ZtqNUBSKhSDl+qS46+7TDaIacLtJXbMLkWuThKfYebQEwhyxsex+BnSThUaZS1PizU1aKybHfgsjp/IJPTGjWqz5c7jqGQAKKXgMWcZnEN8R5/oFeurtHYGiuAsQCkkZ8ueZdldXMpKCf2o6CEq/f8mDLw9ffVt5Q+8Ftm+Uq7NjIJBdGBpXFTGgR5ENK1DPKXRoE6i8JKIfHqKp2kgizgQ45syX6IG9dfLOcCyHU/raXungR5SuvVSwLLqKgVI9eddGNhHbIlrRGbnhQK8uhEKw6ZAT+PW+qaesa4DGyNPzoiNr0bLjN3fRJmaNySZaVvdeFPhR1+vew5wQEO4SSVXihFmmHMYihxWfdaY=
  file: ArithmeticDate.framework.zip
  skip_cleanup: true
  on:
    repo: z4r/arithmetic-date
    tags: true
